name: s_multiloginp
description: Siltium plugin to log in app with email & social network.
version: 1.0.1
homepage: https://github.com/siltium-labs/flutter-multi-login/tree/development

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=3.19.6"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  cupertino_icons: ^1.0.8
  # Librerías para inicio de sesión con redes sociales
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1
  sign_in_with_apple: ^6.1.1
  crypto: ^3.0.3
  twitter_login: ^4.4.2
  linkedin_login: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.example.s_multiloginp
        pluginClass: SMultiloginpPlugin
      ios:
        pluginClass: SMultiloginpPlugin

  assets:
    - assets/
